version: '3'

services:
  # Example: A service named "app"
  app:
    image: python:3
    command: bash -c "python app.py"
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app

networks:
  default:
    driver: bridge
