# YAML/Docker - Medium

version: '3'

services:
  web-server:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - database-server
    networks:
      - my-network

database-server:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - my-network


networks:
   my-network:
    driver: bridge


