# Kubernetes/YAML - Easy

# TODO: Create a YAML configuration file for a Kubernetes Deployment that meets the following criteria:
# Deploys 3 replicas of the nginx container.
# Sets the label app to web.
# Maps port 80 in the container to port 8080 on the host.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          hostPort: 8080
