# Kubernetes/YAML - Easy

# TODO: Create a YAML configuration file for a Kubernetes Deployment that meets the following criteria:
# Deploys 3 replicas of the nginx container.
# Sets the label app to web.
# Maps port 80 in the container to port 8080 on the host.
---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s
  labels:
    name: k8s

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: k8s-sa
  namespace: k8s

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-config
  namespace: k8s
data:
  k8s_port: "8080"
  k8s_app_prefix: api
  k8s_app_name: k8s-test

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-svc
  namespace: k8s
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
    template:
      metadata:
        labels:
          app: web
      spec:
        containers:
          - name: web
            image: nginx
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 80
            env:
              - name: PORT
                valueFrom:
                  configMapKeyRef:
                    name: k8s-config
                    key: k8s_port
              - name: APP_PREFIX
                valueFrom:
                  configMapKeyRef:
                    name: k8s-config
                    key: k8s_app_prefix
              - name: APP_NAME
                valueFrom:
                  configMapKeyRef:
                    name: k8s-config
                    key: k8s_app_name

